-- Minimal tables used by controllers

CREATE TABLE IF NOT EXISTS stellar_deposit (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uid INT NOT NULL,
  txn_hash_stellar VARCHAR(128) DEFAULT NULL,
  txn_hash_yemchain VARCHAR(128) DEFAULT NULL,
  amount DECIMAL(32,2) NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stellar_withdraw (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uid INT NOT NULL,
  address VARCHAR(128) NOT NULL,
  txn_hash_stellar VARCHAR(128) DEFAULT NULL,
  txn_hash_yemchain VARCHAR(128) DEFAULT NULL,
  amount DECIMAL(32,2) NOT NULL DEFAULT 0,
  trustline TINYINT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
